from pydantic import BaseModel, Field


class StrategyInsight(BaseModel):
    """
    Standardized format for strategic insights generated by the Analyst Team.
    These are consumed by the LLMAdvisor (Race Engineer).
    """

    summary: str = Field(
        ..., description="A short summary of the strategic observation."
    )
    recommendation: str = Field(
        ..., description="The team's actionable recommendation."
    )
    criticality: int = Field(
        1,
        description="1-5. 5 means the Race Engineer must interrupt the driver immediately.",
    )
