package intelligence

import (
	"context"
	"database/sql"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/rs/zerolog/log"

	"github.com/tusharbhardwaj/race-engineer/telemetry-core/internal/insights"
	"github.com/tusharbhardwaj/race-engineer/telemetry-core/internal/models"
)

// Analyst runs a background strategy analysis loop every 15 seconds.
// It queries DuckDB for telemetry trends, reads workspace/*.md files for
// historical context, and uses Gemini with tool calling to generate strategic
// insights. Replaces opencode_agent.py.
type Analyst struct {
	provider     LLMProvider
	reader       *sql.DB
	workspaceDir string
	rawChan      chan<- models.DrivingInsight
	insightLog   *insights.Log
	cacheLoad    func() *models.RaceState
}

// NewAnalyst creates a strategy analyst goroutine.
func NewAnalyst(
	provider LLMProvider,
	reader *sql.DB,
	workspaceDir string,
	rawChan chan<- models.DrivingInsight,
	insightLog *insights.Log,
	cacheLoad func() *models.RaceState,
) *Analyst {
	return &Analyst{
		provider:     provider,
		reader:       reader,
		workspaceDir: workspaceDir,
		rawChan:      rawChan,
		insightLog:   insightLog,
		cacheLoad:    cacheLoad,
	}
}

// Run starts the 15-second analysis loop. Blocks until ctx is cancelled.
func (a *Analyst) Run(ctx context.Context) {
	ticker := time.NewTicker(15 * time.Second)
	defer ticker.Stop()

	log.Info().Str("workspace", a.workspaceDir).Msg("Strategy analyst started (15s loop)")

	for {
		select {
		case <-ctx.Done():
			log.Info().Msg("Strategy analyst stopping")
			return
		case <-ticker.C:
			a.analyze(ctx)
		}
	}
}

// analyze performs a single analysis cycle.
func (a *Analyst) analyze(ctx context.Context) {
	// 1. Read workspace context.
	workspaceCtx := a.readWorkspaceFiles()

	// 2. Query telemetry data from DuckDB.
	telemetryData := a.queryTelemetry(ctx)
	if telemetryData == "" {
		log.Debug().Msg("No telemetry data available, skipping analysis")
		return
	}

	// 3. Gather recent insight history to avoid duplicates.
	var insightHistory string
	if a.insightLog != nil {
		insightHistory = a.insightLog.FormatForLLM(20)
	}

	// 4. Build prompt with tool calling.
	systemInstruction := fmt.Sprintf(
		"You are an OpenCode Agent acting as a backend Strategy Analyst for an F1 team. "+
			"You sit in the remote garage with LIVE access to the current session's telemetry database. "+
			"The data below is from the CURRENT session happening RIGHT NOW — not historical data. "+
			"Your job is to analyze live race conditions, competitor strategies, and cross-reference "+
			"with workspace learnings to generate actionable strategy insights.\n\n"+
			"Here is your Workspace Knowledge (historical context):\n%s\n\n"+
			"IMPORTANT — DUPLICATE PREVENTION:\n"+
			"Below is the log of ALL insights recently generated by you and other systems (engine rules, webhooks, etc.). "+
			"Before sending any insight, you MUST review this log carefully. Do NOT send an insight if:\n"+
			"- The same topic was already covered in the last few minutes\n"+
			"- Another system already alerted on the same issue (e.g., tire wear warning already sent by engine)\n"+
			"- The situation has not materially changed since the last insight on that topic\n"+
			"Only send a NEW insight if you have genuinely new information, a changed recommendation, or the situation has escalated.\n\n"+
			"%s\n\n"+
			"If you see a situation that warrants action (e.g., tire wear crossing a critical threshold "+
			"mentioned in past_learnings.md) AND it has NOT already been covered above, "+
			"use the `send_insight_to_race_engineer` tool to alert the Race Engineer. "+
			"If everything is fine or already covered, just say 'No action needed'.",
		workspaceCtx, insightHistory,
	)

	prompt := fmt.Sprintf("Live Database Query Results:\n%s\n\nReview the insight history above, then decide: do we need to send a NEW insight?", telemetryData)

	tools := []ToolDef{
		{
			Name:        "send_insight_to_race_engineer",
			Description: "Sends a strategic insight to the Race Engineer. Use when you have formed a concrete recommendation based on telemetry and workspace knowledge.",
			Parameters: []ToolParam{
				{Name: "summary", Type: "string", Description: "A short description of the current situation (e.g. 'Rear right wear is 46%')."},
				{Name: "recommendation", Type: "string", Description: "What the driver should do (e.g. 'Box this lap for hard tires')."},
				{Name: "criticality", Type: "integer", Description: "Priority level 1 to 5. 5 is extremely critical (immediate pit stop required)."},
			},
			Required: []string{"summary", "recommendation", "criticality"},
		},
	}

	cfg := ProviderConfig{
		Temperature: 0.2,
		MaxTokens:   500,
	}

	result, err := a.provider.CompleteWithTools(ctx, systemInstruction, prompt, cfg, tools)
	if err != nil {
		log.Error().Err(err).Msg("Analyst: LLM tool call failed")
		return
	}

	// 4. Execute any tool calls.
	for _, tc := range result.ToolCalls {
		if tc.Name == "send_insight_to_race_engineer" {
			summary, _ := tc.Args["summary"].(string)
			recommendation, _ := tc.Args["recommendation"].(string)
			criticality := 3
			if c, ok := tc.Args["criticality"].(float64); ok {
				criticality = int(c)
			}

			log.Info().
				Str("summary", summary).
				Str("recommendation", recommendation).
				Int("criticality", criticality).
				Msg("Analyst tool call: send_insight_to_race_engineer")

			insight := models.DrivingInsight{
				Message:  fmt.Sprintf("%s — %s", summary, recommendation),
				Type:     "strategy",
				Priority: criticality,
			}

			if a.insightLog != nil {
				a.insightLog.Record("analyst", insight)
			}

			select {
			case a.rawChan <- insight:
			default:
				log.Warn().Msg("Raw insight channel full, dropping analyst insight")
			}
		}
	}

	if len(result.ToolCalls) == 0 && result.Text != "" {
		log.Debug().Str("analysis", result.Text).Msg("Analyst: no action needed")
	}
}

// HandleStrategyWebhook processes a POST /api/strategy request from external agents.
func (a *Analyst) HandleStrategyWebhook(payload models.StrategyPayload) {
	insight := models.DrivingInsight{
		Message:  fmt.Sprintf("%s — %s", payload.Summary, payload.Recommendation),
		Type:     "strategy",
		Priority: payload.Criticality,
	}

	if a.insightLog != nil {
		a.insightLog.Record("webhook", insight)
	}

	select {
	case a.rawChan <- insight:
		log.Info().Int("criticality", payload.Criticality).Msg("Strategy webhook insight accepted")
	default:
		log.Warn().Msg("Raw insight channel full, dropping webhook insight")
	}
}

// readWorkspaceFiles reads all .md files from the workspace directory.
func (a *Analyst) readWorkspaceFiles() string {
	var sb strings.Builder
	entries, err := os.ReadDir(a.workspaceDir)
	if err != nil {
		log.Warn().Err(err).Msg("Could not read workspace directory")
		return ""
	}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".md") {
			continue
		}
		data, err := os.ReadFile(filepath.Join(a.workspaceDir, e.Name()))
		if err != nil {
			continue
		}
		sb.WriteString(fmt.Sprintf("\n\n--- %s ---\n%s", e.Name(), string(data)))
	}
	return sb.String()
}

// playerIndex returns the current player car index from the live cache.
// Falls back to 0 if no state is available.
func (a *Analyst) playerIndex() int {
	if a.cacheLoad != nil {
		if state := a.cacheLoad(); state != nil {
			return int(state.PlayerCarIndex)
		}
	}
	return 0
}

// queryTelemetry queries DuckDB for recent telemetry data across multiple tables.
func (a *Analyst) queryTelemetry(ctx context.Context) string {
	if a.reader == nil {
		return ""
	}

	idx := a.playerIndex()
	var sections []string

	// 1. Session identity — track, session type, total laps, weather, pit windows, safety car
	rows := a.queryRows(ctx, `SELECT track_id, session_type, total_laps, track_length,
		weather, track_temperature, air_temperature, rain_percentage,
		safety_car_status, session_time_left,
		pit_stop_window_ideal_lap, pit_stop_window_latest_lap
		FROM session_data ORDER BY timestamp DESC LIMIT 1`)
	if len(rows) > 0 {
		r := rows[0]
		track := trackName(int(toFloat(r["track_id"])))
		sessType := sessionTypeName(int(toFloat(r["session_type"])))
		totalLaps := int(toFloat(r["total_laps"]))
		trackLen := int(toFloat(r["track_length"]))
		sections = append(sections, fmt.Sprintf("SESSION: %s at %s | %d laps | Track length: %dm", sessType, track, totalLaps, trackLen))

		weather := weatherName(uint8(toFloat(r["weather"])))
		sections = append(sections, fmt.Sprintf("Weather: %s, Track: %dC, Air: %dC, Rain probability: %d%%",
			weather, int(toFloat(r["track_temperature"])),
			int(toFloat(r["air_temperature"])),
			int(toFloat(r["rain_percentage"]))))

		sc := uint8(toFloat(r["safety_car_status"]))
		if sc > 0 {
			sections = append(sections, fmt.Sprintf("SAFETY CAR: %s", safetyCarName(sc)))
		}

		idealPit := int(toFloat(r["pit_stop_window_ideal_lap"]))
		latestPit := int(toFloat(r["pit_stop_window_latest_lap"]))
		if idealPit > 0 || latestPit > 0 {
			sections = append(sections, fmt.Sprintf("Pit window: ideal lap %d, latest lap %d", idealPit, latestPit))
		}

		timeLeft := int(toFloat(r["session_time_left"]))
		if timeLeft > 0 {
			sections = append(sections, fmt.Sprintf("Session time remaining: %dm %ds", timeLeft/60, timeLeft%60))
		}
	}

	// 2. Our car position, lap, gaps
	rows = a.queryRows(ctx, fmt.Sprintf(`SELECT car_position, current_lap_num, last_lap_time_in_ms,
		delta_to_car_in_front_in_ms, delta_to_race_leader_in_ms,
		num_pit_stops, pit_status
		FROM lap_data WHERE car_index = %d ORDER BY timestamp DESC LIMIT 1`, idx))
	if len(rows) > 0 {
		r := rows[0]
		pos := int(toFloat(r["car_position"]))
		lap := int(toFloat(r["current_lap_num"]))
		lastLap := toFloat(r["last_lap_time_in_ms"]) / 1000
		gapFront := toFloat(r["delta_to_car_in_front_in_ms"]) / 1000
		gapLeader := toFloat(r["delta_to_race_leader_in_ms"]) / 1000
		pits := int(toFloat(r["num_pit_stops"]))
		pitStatus := int(toFloat(r["pit_status"]))

		posLine := fmt.Sprintf("POSITION: P%d, Lap %d, Pit stops: %d", pos, lap, pits)
		if pitStatus == 1 {
			posLine += " [IN PIT LANE]"
		} else if pitStatus == 2 {
			posLine += " [PITTING THIS LAP]"
		}
		sections = append(sections, posLine)

		if lastLap > 0 {
			sections = append(sections, fmt.Sprintf("Last lap: %.3fs", lastLap))
		}
		if gapFront > 0 {
			sections = append(sections, fmt.Sprintf("Gap to car ahead: +%.3fs", gapFront))
		}
		if gapLeader > 0 && pos > 1 {
			sections = append(sections, fmt.Sprintf("Gap to leader: +%.3fs", gapLeader))
		}
	}

	// 3. Nearby competitors (cars around us for strategy context)
	rows = a.queryRows(ctx, fmt.Sprintf(`WITH our_pos AS (
		SELECT car_position FROM lap_data WHERE car_index = %d ORDER BY timestamp DESC LIMIT 1
	)
	SELECT l.car_index, l.car_position, l.current_lap_num, l.num_pit_stops,
		l.delta_to_car_in_front_in_ms, l.pit_status,
		s.actual_tyre_compound, s.tyres_age_laps
	FROM lap_data l
	LEFT JOIN car_status s ON l.car_index = s.car_index
		AND s.timestamp = (SELECT MAX(timestamp) FROM car_status WHERE car_index = l.car_index)
	WHERE l.car_index != %d
		AND l.car_position BETWEEN (SELECT car_position FROM our_pos) - 3 AND (SELECT car_position FROM our_pos) + 3
		AND l.timestamp = (SELECT MAX(timestamp) FROM lap_data WHERE car_index = l.car_index)
	ORDER BY l.car_position`, idx, idx))
	if len(rows) > 0 {
		sections = append(sections, "Nearby competitors:")
		for _, r := range rows {
			compound := compoundName(uint8(toFloat(r["actual_tyre_compound"])))
			tireAge := int(toFloat(r["tyres_age_laps"]))
			pits := int(toFloat(r["num_pit_stops"]))
			pos := int(toFloat(r["car_position"]))
			pitStatus := int(toFloat(r["pit_status"]))
			line := fmt.Sprintf("  P%d Car#%d | %s (%d laps old) | %d stops",
				pos, int(toFloat(r["car_index"])), compound, tireAge, pits)
			if pitStatus > 0 {
				line += " [PITTING]"
			}
			sections = append(sections, line)
		}
	}

	// 4. Tire wear trend (last 3 samples)
	rows = a.queryRows(ctx, fmt.Sprintf(`SELECT tyres_wear_fl, tyres_wear_fr, tyres_wear_rl, tyres_wear_rr
		FROM car_damage WHERE car_index = %d ORDER BY timestamp DESC LIMIT 3`, idx))
	if len(rows) > 0 {
		sections = append(sections, "Tire wear trend (newest first):")
		for _, r := range rows {
			sections = append(sections, fmt.Sprintf("  FL:%.1f%% FR:%.1f%% RL:%.1f%% RR:%.1f%%",
				r["tyres_wear_fl"], r["tyres_wear_fr"], r["tyres_wear_rl"], r["tyres_wear_rr"]))
		}
	}

	// 5. Car damage
	rows = a.queryRows(ctx, fmt.Sprintf(`SELECT front_left_wing_damage, front_right_wing_damage,
		rear_wing_damage, floor_damage, diffuser_damage, sidepod_damage,
		gear_box_damage, engine_damage
		FROM car_damage WHERE car_index = %d ORDER BY timestamp DESC LIMIT 1`, idx))
	if len(rows) > 0 {
		r := rows[0]
		var dmg []string
		addDmg := func(name string, val float64) {
			if val > 0 {
				dmg = append(dmg, fmt.Sprintf("%s:%d%%", name, int(val)))
			}
		}
		addDmg("FL Wing", toFloat(r["front_left_wing_damage"]))
		addDmg("FR Wing", toFloat(r["front_right_wing_damage"]))
		addDmg("Rear Wing", toFloat(r["rear_wing_damage"]))
		addDmg("Floor", toFloat(r["floor_damage"]))
		addDmg("Diffuser", toFloat(r["diffuser_damage"]))
		addDmg("Sidepod", toFloat(r["sidepod_damage"]))
		addDmg("Gearbox", toFloat(r["gear_box_damage"]))
		addDmg("Engine", toFloat(r["engine_damage"]))
		if len(dmg) > 0 {
			sections = append(sections, "CAR DAMAGE: "+strings.Join(dmg, ", "))
		}
	}

	// 6. Fuel and compound
	rows = a.queryRows(ctx, fmt.Sprintf(`SELECT fuel_in_tank, fuel_remaining_laps, actual_tyre_compound,
		tyres_age_laps, ers_store_energy, ers_deploy_mode
		FROM car_status WHERE car_index = %d ORDER BY timestamp DESC LIMIT 1`, idx))
	if len(rows) > 0 {
		r := rows[0]
		compound := compoundName(uint8(toFloat(r["actual_tyre_compound"])))
		ersPct := toFloat(r["ers_store_energy"]) / 4_000_000.0 * 100
		ersMode := ersModeName(uint8(toFloat(r["ers_deploy_mode"])))
		sections = append(sections, fmt.Sprintf("Fuel: %.1fkg (%.1f laps remaining) | Compound: %s, Age: %d laps | ERS: %.0f%% (%s)",
			toFloat(r["fuel_in_tank"]), toFloat(r["fuel_remaining_laps"]),
			compound, int(toFloat(r["tyres_age_laps"])),
			ersPct, ersMode))
	}

	// 7. Lap time progression (last 5 laps for trend analysis)
	rows = a.queryRows(ctx, fmt.Sprintf(`SELECT lap_num, lap_time_in_ms, sector1_time_in_ms, sector2_time_in_ms, sector3_time_in_ms
		FROM session_history WHERE car_index = %d AND lap_time_in_ms > 0 ORDER BY lap_num DESC LIMIT 5`, idx))
	if len(rows) > 0 {
		sections = append(sections, "Lap time progression (newest first):")
		for _, r := range rows {
			sections = append(sections, fmt.Sprintf("  Lap %d: %.3fs (S1:%.3f S2:%.3f S3:%.3f)",
				int(toFloat(r["lap_num"])),
				toFloat(r["lap_time_in_ms"])/1000,
				toFloat(r["sector1_time_in_ms"])/1000,
				toFloat(r["sector2_time_in_ms"])/1000,
				toFloat(r["sector3_time_in_ms"])/1000))
		}
	}

	if len(sections) == 0 {
		return ""
	}
	return strings.Join(sections, "\n")
}

// queryRows executes a SQL query and returns results as a slice of maps.
func (a *Analyst) queryRows(ctx context.Context, query string) []map[string]any {
	rows, err := a.reader.QueryContext(ctx, query)
	if err != nil {
		log.Debug().Err(err).Msg("Analyst query failed")
		return nil
	}
	defer rows.Close()

	cols, err := rows.Columns()
	if err != nil {
		return nil
	}

	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		if err := rows.Scan(ptrs...); err != nil {
			continue
		}
		row := make(map[string]any, len(cols))
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}
	return results
}

// toFloat converts an any value to float64 for formatting.
func toFloat(v any) float64 {
	switch val := v.(type) {
	case float64:
		return val
	case float32:
		return float64(val)
	case int64:
		return float64(val)
	case int32:
		return float64(val)
	case int:
		return float64(val)
	default:
		return 0
	}
}
