from pydantic import BaseModel, Field


class TelemetryTick(BaseModel):
    """
    Standardized format for incoming telemetry ticks.
    All properties are typically calculated 20-60 times per second in a racing sim.
    """

    speed: float = Field(..., description="Current speed in km/h")
    gear: int = Field(..., description="Current gear. 0 is Neutral, -1 is Reverse.")
    throttle: float = Field(
        ..., ge=0.0, le=1.0, description="Throttle input (0.0 to 1.0)"
    )
    brake: float = Field(..., ge=0.0, le=1.0, description="Brake input (0.0 to 1.0)")
    steering: float = Field(
        0.0, ge=-1.0, le=1.0, description="Steering input (-1.0 to 1.0)"
    )

    # Engine & Tires
    engine_rpm: int = Field(..., description="Engine Revolutions Per Minute")
    tire_wear_fl: float = Field(0.0, description="Front Left Tire Wear percentage")
    tire_wear_fr: float = Field(0.0, description="Front Right Tire Wear percentage")
    tire_wear_rl: float = Field(0.0, description="Rear Left Tire Wear percentage")
    tire_wear_rr: float = Field(0.0, description="Rear Right Tire Wear percentage")

    # Race Context
    lap: int = Field(1, description="Current lap number")
    track_position: float = Field(
        0.0,
        ge=0.0,
        le=1.0,
        description="Position around the track (0.0 is start/finish line)",
    )

    # Track details
    sector: int = Field(1, ge=1, le=3, description="Current track sector")


class DrivingInsight(BaseModel):
    """
    Standardized format for insights generated by the Feedback Engine.
    """

    message: str = Field(..., description="The spoken text to deliver to the driver.")
    type: str = Field(
        ...,
        description="Type of insight: 'warning', 'info', 'encouragement', 'strategy'",
    )
    priority: int = Field(
        1,
        description="Priority level (1 is low, 5 is critical). Higher priority interrupts lower.",
    )


class DriverQuery(BaseModel):
    """
    Standardized format for intents or queries asked by the driver.
    """

    query: str = Field(..., description="The recognized text from the driver's speech.")
    confidence: float = Field(1.0, description="Confidence score from STT (0.0 to 1.0)")


class TalkLevelPayload(BaseModel):
    """
    Payload for adjusting the Race Engineer's talk level (verbosity).
    """

    talk_level: int = Field(
        5, ge=1, le=10, description="Talk level from 1 (quiet) to 10 (chatty)"
    )
