package models

// TelemetryTick represents a standardized format for incoming telemetry ticks.
// All properties are typically calculated 20-60 times per second in a racing sim.
type TelemetryTick struct {
	Speed    float64 `json:"speed" db:"speed"`       // Current speed in km/h
	Gear     int     `json:"gear" db:"gear"`         // Current gear. 0 is Neutral, -1 is Reverse.
	Throttle float64 `json:"throttle" db:"throttle"` // Throttle input (0.0 to 1.0)
	Brake    float64 `json:"brake" db:"brake"`       // Brake input (0.0 to 1.0)
	Steering float64 `json:"steering" db:"steering"` // Steering input (-1.0 to 1.0)

	// Engine & Tires
	EngineRPM  int     `json:"engine_rpm" db:"engine_rpm"`     // Engine Revolutions Per Minute
	TireWearFL float64 `json:"tire_wear_fl" db:"tire_wear_fl"` // Front Left Tire Wear percentage
	TireWearFR float64 `json:"tire_wear_fr" db:"tire_wear_fr"` // Front Right Tire Wear percentage
	TireWearRL float64 `json:"tire_wear_rl" db:"tire_wear_rl"` // Rear Left Tire Wear percentage
	TireWearRR float64 `json:"tire_wear_rr" db:"tire_wear_rr"` // Rear Right Tire Wear percentage

	// Race Context
	Lap           int     `json:"lap" db:"lap"`                       // Current lap number
	TrackPosition float64 `json:"track_position" db:"track_position"` // Position around the track (0.0 is start/finish line)

	// Track details
	Sector int `json:"sector" db:"sector"` // Current track sector
	
	Timestamp int64 `json:"timestamp" db:"timestamp"` // Unix timestamp in milliseconds when tick was received
}

// DrivingInsight represents standardized format for insights generated by the Feedback Engine.
type DrivingInsight struct {
	Message  string `json:"message"`  // The spoken text to deliver to the driver.
	Type     string `json:"type"`     // Type of insight: 'warning', 'info', 'encouragement', 'strategy'
	Priority int    `json:"priority"` // Priority level (1 is low, 5 is critical). Higher priority interrupts lower.
}

// DriverQuery represents a standardized format for intents or queries asked by the driver.
type DriverQuery struct {
	Query      string  `json:"query"`      // The recognized text from the driver's speech.
	Confidence float64 `json:"confidence"` // Confidence score from STT (0.0 to 1.0)
}

// TalkLevelPayload represents a payload for adjusting the Race Engineer's talk level (verbosity).
type TalkLevelPayload struct {
	TalkLevel int `json:"talk_level"` // Talk level from 1 (quiet) to 10 (chatty)
}

// VerbosityPayload is the request body for POST /api/settings/verbosity.
type VerbosityPayload struct {
	Verbosity int `json:"verbosity"` // 1 (terse) to 10 (detailed)
}

// StrategyPayload is the JSON body pushed to the Python UI via POST /api/strategy.
// Matches the Python StrategyPayload Pydantic model exactly.
type StrategyPayload struct {
	Summary        string `json:"summary"`
	Recommendation string `json:"recommendation"`
	Criticality    int    `json:"criticality"`
}

// SQLQueryPayload is the request body for POST /api/query.
type SQLQueryPayload struct {
	SQL string `json:"sql"`
}

// TelemetryModePayload is the request body for POST /api/settings/mode.
type TelemetryModePayload struct {
	Mode    string `json:"mode"`              // "mock" or "real"
	Host    string `json:"host,omitempty"`
	Port    int    `json:"port,omitempty"`
	UDPMode string `json:"udp_mode,omitempty"` // "broadcast" or "unicast"
}

// ParsedPacket carries a packet ID and the raw bytes through the ingestion pipeline.
type ParsedPacket struct {
	PacketID uint8
	Data     []byte
}

// MockOverrides allows the dashboard to manually override physics/weather in mock mode.
type MockOverrides struct {
	TireWearMultiplier float32 `json:"tire_wear_multiplier"`
	FuelBurnMultiplier float32 `json:"fuel_burn_multiplier"`
	TireTempOffset     float32 `json:"tire_temp_offset"`
	WeatherOverride    *int    `json:"weather_override"` // 0-5, nil if no override
	RainPercentage     *int    `json:"rain_percentage"`  // 0-100, nil if no override
}
